name: Node.js Build and Test

on:
  workflow_call:
    inputs:
      package-path:
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: cd ${{ inputs.package-path }}
    - run: npm ci
    - run: npm test
